spring.application.name=LoginSystem

# =========================
# Database - Aiven MySQL
# =========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =========================
# Server
# =========================

server.port=${PORT:8080}

## =========================
## Gmail SMTP
## =========================
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=465
#spring.mail.username=loginsystembyddoc@gmail.com
#spring.mail.password=${MAIL_PASSWORD}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.starttls.enable=false
#
#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.writetimeout=10000



# =========================
# Resend
# =========================

resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL}


# =========================
# JWT
# =========================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# =========================
# Groq AI
# =========================

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile